### ISSUE TITLE
Present tense on past holidays

### ISSUE THREAD

**Issue by oddurs** [OSSP2014/fridagar.is#19]
Currently displays 'eru' instead of 'voru' when viewing `holidaysInCurrentMonth.length` for dates prior to current.

![Present tense bug](https://www.evernote.com/shard/s82/sh/4dd17d95-2b0c-45ab-9792-cb63554473d8/0e6064eda213b34afb7b224035ba43ab/deep/0/Frídagar.is---Hvenær-er-frí-.png)

`app/views/main.html`

``` html
<p>Það eru <span class="color-text">{{holidaysInCurrentMonth.length}}</span> frídagar í þessum mánuði.</p>
```

**Comment by bjerkins** [comment]
Good catch. Will fix it soon
